from collections.abc import Sequence
from datetime import date, datetime
from typing import NamedTuple, Protocol

from orc.dal.audio import pyaudio as _audio_default
from orc.dal.chromecast import pychromecast as _chromecast_default
from orc.dal.hubitat import http as _hubitat_default
from orc.dal.mqtt import hubitat as _mqtt_default
from orc.dal.secrets import bws as _secrets_default
from orc.model import (
    ButtonListener,
    Capability,
    Configs,
    DeviceEnum,
    DeviceState,
    Listener,
    RetryStats,
    Secrets,
    SoundState,
    WeatherCondition,
)


class SecretsService(Protocol):
    def fetch_secrets(self) -> Secrets: ...


class WeatherService(Protocol):
    def fetch_weather(self, now: datetime, lat: float, lon: float) -> frozenset[WeatherCondition]: ...


class HolidayService(Protocol):
    def market_holiday(self, today: date) -> bool: ...


class MqttService(Protocol):
    def start(self) -> None: ...
    def fetch_hubitat_config(self, secrets: Secrets, timeout: float = 3.0) -> dict[str, tuple[int, frozenset[Capability]]]: ...
    def fetch_light_states(self, lights: Sequence[DeviceEnum]) -> Configs: ...
    def publish_light(self, light: DeviceEnum, on: bool | None = None, brightness: int | None = None) -> None: ...
    def snapshot(self) -> list[DeviceState]: ...
    def add_listener(self, fn: Listener) -> None: ...
    def add_button_listener(self, fn: ButtonListener) -> None: ...
    def add_external_listener(self, fn: Listener) -> None: ...


class AudioService(Protocol):
    def speak(self, device: DeviceEnum, text: str) -> None: ...
    def alert(self, device: DeviceEnum, path: str) -> None: ...
    def set_volume(self, device: DeviceEnum, lvl: int) -> None: ...


class ChromecastService(Protocol):
    def fetch_state(self, device: DeviceEnum) -> SoundState: ...
    def fetch_youtube_stream_metadata(self, id: str) -> tuple[str, str]: ...
    def speak(self, device: DeviceEnum, text: str) -> None: ...
    def pause(self, device: DeviceEnum) -> None: ...
    def play(self, device: DeviceEnum, stream_url: str, title: str) -> None: ...
    def resume(self, device: DeviceEnum) -> None: ...
    def stop(self, device: DeviceEnum) -> None: ...
    def set_volume(self, device: DeviceEnum, lvl: int) -> None: ...


class BlasterService(Protocol):
    def set_ac(self, device: DeviceEnum, codes_file: str, mode: str, fan: str, temp: int) -> None: ...
    def tv_toggle(self, device: DeviceEnum, codes_file: str) -> None: ...
    def ac_off(self, device: DeviceEnum, codes_file: str) -> None: ...


class HubitatService(Protocol):
    def reboot(self) -> None: ...
    def fetch_retry_stats(self) -> tuple[RetryStats, ...]: ...


class Provider(NamedTuple):
    secrets: SecretsService | None = _secrets_default
    weather: WeatherService | None = None
    holiday: HolidayService | None = None
    mqtt: MqttService | None = _mqtt_default
    chromecast: ChromecastService | None = _chromecast_default
    blaster: BlasterService | None = None
    hubitat: HubitatService | None = _hubitat_default
    audio: AudioService | None = _audio_default
