from collections.abc import Callable
from datetime import date, datetime
from typing import Any, NamedTuple, Protocol

from orc.dal.audio import pyaudio as _audio_default
from orc.dal.chromecast import pychromecast as _chromecast_default
from orc.dal.hubitat import http as _hubitat_default
from orc.dal.mqtt import paho as _mqtt_default
from orc.dal.push import webpush as _push_default
from orc.dal.secrets import bws as _secrets_default
from orc.model import (
    Capability,
    DeviceEnum,
    DeviceState,
    Listener,
    MediaUrl,
    Message,
    Notification,
    PushSubscription,
    RetryStats,
    Secrets,
    SoundState,
    Status,
    WeatherCondition,
)


class Backend(Protocol):
    REQUIRED_SECRETS: dict[str, Callable[[str], Any]]


class SecretsService(Backend, Protocol):
    def fetch_secrets(self) -> Secrets: ...


class WeatherService(Backend, Protocol):
    def fetch_weather(self, now: datetime, lat: float, lon: float) -> frozenset[WeatherCondition]: ...
    def fetch_temperature(self, now: datetime, lat: float, lon: float) -> float: ...


class HolidayService(Backend, Protocol):
    def market_holiday(self, today: date) -> bool: ...


class Codec(Protocol):
    namespaces: tuple[str, ...]
    device_types: tuple[str, ...]

    def attach(self, publish: Callable[[Message], None]) -> None: ...
    def decode(self, topic: str, doc: dict[str, Any]) -> tuple[Status, ...]: ...
    def encode(self, device: DeviceEnum, command: Any) -> tuple[Message, ...]: ...
    def snapshot(self) -> tuple[DeviceState, ...]: ...
    def start(self) -> None: ...


class MqttService(Backend, Protocol):
    def start(self) -> None: ...
    def register(self, codec: Codec) -> None: ...
    def add_listener(self, fn: Listener) -> None: ...
    def add_external_listener(self, fn: Listener) -> None: ...
    def snapshot(self) -> list[DeviceState]: ...
    def command(self, device: DeviceEnum, value: Any) -> None: ...
    def fetch_hubitat_config(self, secrets: Secrets, timeout: float = 3.0) -> dict[str, tuple[str, frozenset[Capability]]]: ...


class AudioService(Backend, Protocol):
    def speak(self, device: DeviceEnum, text: str) -> None: ...
    def alert(self, device: DeviceEnum, path: str) -> None: ...
    def set_volume(self, device: DeviceEnum, lvl: int) -> None: ...
    def fetch_state(self, device: DeviceEnum) -> SoundState: ...


class ChromecastService(Backend, Protocol):
    def fetch_state(self, device: DeviceEnum) -> SoundState: ...
    def fetch_youtube_stream_metadata(self, id: str) -> tuple[str, str]: ...
    def speak(self, device: DeviceEnum, text: str) -> None: ...
    def pause(self, device: DeviceEnum) -> None: ...
    def play(self, device: DeviceEnum, stream_url: MediaUrl, title: str) -> None: ...
    def resume(self, device: DeviceEnum) -> None: ...
    def stop(self, device: DeviceEnum) -> None: ...
    def set_volume(self, device: DeviceEnum, lvl: int) -> None: ...


class BlasterService(Backend, Protocol):
    def tv_toggle(self, device: DeviceEnum, codes_file: str) -> None: ...


class PushService(Backend, Protocol):
    def public_key(self) -> str: ...
    def send(self, subscription: PushSubscription, title: str, body: str, notification: Notification) -> None: ...


class HubitatService(Backend, Protocol):
    def reboot(self) -> None: ...
    def fetch_retry_stats(self) -> tuple[RetryStats, ...]: ...


class Provider(NamedTuple):
    secrets: SecretsService | None = _secrets_default
    weather: WeatherService | None = None
    holiday: HolidayService | None = None
    mqtt: MqttService | None = _mqtt_default
    chromecast: ChromecastService | None = _chromecast_default
    blaster: BlasterService | None = None
    hubitat: HubitatService | None = _hubitat_default
    audio: AudioService | None = _audio_default
    push: PushService | None = _push_default
